Microsoft Windows [Version 10.0.18363.836]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\Abhishek bhatt>cd Documents

C:\Users\Abhishek bhatt\Documents>cd dl project

C:\Users\Abhishek bhatt\Documents\dl project>cd anomaly

C:\Users\Abhishek bhatt\Documents\dl project\anomaly>cd My_Annomaly-detector
The system cannot find the path specified.

C:\Users\Abhishek bhatt\Documents\dl project\anomaly>cd My_Anomaly-detector

C:\Users\Abhishek bhatt\Documents\dl project\anomaly\My_Anomaly-detector>cd imagesearch

C:\Users\Abhishek bhatt\Documents\dl project\anomaly\My_Anomaly-detector\imagesearch>python __init__.py

C:\Users\Abhishek bhatt\Documents\dl project\anomaly\My_Anomaly-detector\imagesearch>python features.py

C:\Users\Abhishek bhatt\Documents\dl project\anomaly\My_Anomaly-detector\imagesearch>cd ..

C:\Users\Abhishek bhatt\Documents\dl project\anomaly\My_Anomaly-detector>python train_anomaly_detector.py --dataset forest --model anomaly_detector.model
[INFO] preparing dataset...
[INFO] fitting anomaly detection model...

C:\Users\Abhishek bhatt\Documents\dl project\anomaly\My_Anomaly-detector>python test_anomaly_detector.py --model anomaly_detectorl.model \--image examples/forest_cdmc290.jpg
usage: test_anomaly_detector.py [-h] -m MODEL -i IMAGE
test_anomaly_detector.py: error: the following arguments are required: -i/--image

C:\Users\Abhishek bhatt\Documents\dl project\anomaly\My_Anomaly-detector>python test_anomaly_detector.py --model anomaly_detectorl.model \--image examples/forest_cdmc290.jpg
usage: test_anomaly_detector.py [-h] -m MODEL -i IMAGE
test_anomaly_detector.py: error: the following arguments are required: -i/--image

C:\Users\Abhishek bhatt\Documents\dl project\anomaly\My_Anomaly-detector>python test_anomaly_detector.py --model anomaly_detectorl.model --image examples/forest_cdmc290.jpg
[INFO] loading anomaly detection model...
Traceback (most recent call last):
  File "test_anomaly_detector.py", line 20, in <module>
    model = pickle.loads(open(args["model"], "rb").read())
FileNotFoundError: [Errno 2] No such file or directory: 'anomaly_detectorl.model'

C:\Users\Abhishek bhatt\Documents\dl project\anomaly\My_Anomaly-detector>python test_anomaly_detector.py --model anomaly_detector.model --image examples/forest_cdmc290.jpg
[INFO] loading anomaly detection model...

C:\Users\Abhishek bhatt\Documents\dl project\anomaly\My_Anomaly-detector>python test_anomaly_detector.py --model anomaly_detector.model --image examples/coast_osun52.jpg
[INFO] loading anomaly detection model...

C:\Users\Abhishek bhatt\Documents\dl project\anomaly\My_Anomaly-detector>python test_anomaly_detector.py --model anomaly_detector.model --image examples/abhi.jpg
[INFO] loading anomaly detection model...

C:\Users\Abhishek bhatt\Documents\dl project\anomaly\My_Anomaly-detector>python test_anomaly_detector.py --model anomaly_detector.model --image examples/test1.jpg
[INFO] loading anomaly detection model...

C:\Users\Abhishek bhatt\Documents\dl project\anomaly\My_Anomaly-detector>python train_anomaly_watches_detector.py --dataset watches --model anomaly_watches_detector.model
[INFO] preparing dataset...
[INFO] fitting anomaly detection model...

C:\Users\Abhishek bhatt\Documents\dl project\anomaly\My_Anomaly-detector>python test_anomaly_detector.py --model anomaly_detector.model --image examples/watch3.jpg
python: can't open file 'test_anomaly_detector.py': [Errno 2] No such file or directory

C:\Users\Abhishek bhatt\Documents\dl project\anomaly\My_Anomaly-detector>python test_anomaly_detector.py --model anomaly_detector.model --image examples/watch1.jpg
python: can't open file 'test_anomaly_detector.py': [Errno 2] No such file or directory

C:\Users\Abhishek bhatt\Documents\dl project\anomaly\My_Anomaly-detector>python test_anomaly_detector.py --model anomaly_detector.model --image examples/watch_test.jpg
python: can't open file 'test_anomaly_detector.py': [Errno 2] No such file or directory

C:\Users\Abhishek bhatt\Documents\dl project\anomaly\My_Anomaly-detector>python test_anomaly_detector.py --model anomaly_detector.model --image examples/watch4.jpg
python: can't open file 'test_anomaly_detector.py': [Errno 2] No such file or directory

C:\Users\Abhishek bhatt\Documents\dl project\anomaly\My_Anomaly-detector>python test_anomaly_detector.py --model anomaly_detector.model --image examples/abhi.jpg
python: can't open file 'test_anomaly_detector.py': [Errno 2] No such file or directory

C:\Users\Abhishek bhatt\Documents\dl project\anomaly\My_Anomaly-detector>python test_anomaly_detector.py --model anomaly_detector.model --image examples/watch4.jpg
python: can't open file 'test_anomaly_detector.py': [Errno 2] No such file or directory

C:\Users\Abhishek bhatt\Documents\dl project\anomaly\My_Anomaly-detector>python test_anomaly_detector.py --model anomaly_detector.model --image examples/watch4.jpg
[INFO] loading anomaly detection model...

C:\Users\Abhishek bhatt\Documents\dl project\anomaly\My_Anomaly-detector>python test_anomaly_detector.py --model anomaly_detector.model --image examples/abhi.jpg
[INFO] loading anomaly detection model...

C:\Users\Abhishek bhatt\Documents\dl project\anomaly\My_Anomaly-detector>